/**
 * App-runtime CLI generation.
 *
 * A capability plugin declares the command-line interface its app exposes as
 * data (`app_cli` in plugin.json). This module validates that spec and renders
 * one self-contained file per language: a Node ESM script or a Python argparse
 * module, in the manner of a hand-written app CLI such as a Flask app's own
 * `crm.py`. The generated file embeds the validated spec and a fixed runtime,
 * talks only to the app's HTTP API, and imports nothing from Total Recall, so
 * it keeps working where Total Recall is not installed.
 *
 * Generation is deterministic and never writes: callers decide where the file
 * goes.
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const TEMPLATE_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), 'runtime-cli');
const TEMPLATES = { node: 'node.mjs.tmpl', python: 'python.py.tmpl' };

export const APP_CLI_LANGUAGES = Object.freeze(Object.keys(TEMPLATES));
export const ADAPTER_LANGUAGES = Object.freeze({ 'ssss-app': 'node', nextjs: 'node', react: 'node', flask: 'python' });

import { AppCliSpecError, normalizeAppCliSpec, validateAppCliSpec } from '../plugin-contracts/app-cli.mjs';
export { AppCliSpecError, normalizeAppCliSpec, validateAppCliSpec } from '../plugin-contracts/app-cli.mjs';

export function languageForAdapter(adapter) {
  const language = ADAPTER_LANGUAGES[adapter];
  if (!language) {
    throw new Error(`No app CLI language for adapter '${adapter}'. Known adapters: ${Object.keys(ADAPTER_LANGUAGES).join(', ')}`);
  }
  return language;
}

/** Where the generated file conventionally lives in the app: `bin/<name>.mjs` or `<name>.py`. */
export function appCliPath(name, language) {
  return language === 'python' ? `${name.replace(/-/g, '_')}.py` : `bin/${name}.mjs`;
}

/**
 * Render the app CLI for one language.
 * @param {object} spec  The manifest's `app_cli`.
 * @param {{ language: 'node'|'python', source?: { id: string, version: string } }} options
 * @returns {{ language: string, path: string, content: string, mode: number, sha256: string, spec: object }}
 */
export function generateAppCli(spec, { language, source } = {}) {
  if (!TEMPLATES[language]) throw new Error(`Unknown app CLI language '${language}'. Use one of: ${APP_CLI_LANGUAGES.join(', ')}`);
  const normalized = normalizeAppCliSpec(spec);
  const specJson = JSON.stringify(normalized);
  const specHash = crypto.createHash('sha256').update(specJson).digest('hex');
  const origin = source?.id ? ` from plugin ${source.id}${source.version ? `@${source.version}` : ''}` : '';
  const header = `Generated by Total Recall${origin} (app_cli sha256 ${specHash.slice(0, 12)}). Regenerate instead of editing; it needs no Total Recall install.`;
  // JSON text is a valid JS expression; for Python it is embedded as a JSON
  // string literal (itself valid Python) and decoded with json.loads.
  const specLiteral = language === 'python' ? JSON.stringify(specJson) : JSON.stringify(normalized, null, 2);
  const template = fs.readFileSync(path.join(TEMPLATE_DIR, TEMPLATES[language]), 'utf8');
  if (template.split('__SPEC__').length !== 2 || template.split('__HEADER__').length !== 2) {
    throw new Error(`App CLI template ${TEMPLATES[language]} must contain __SPEC__ and __HEADER__ exactly once`);
  }
  const content = template.replace('__HEADER__', () => header).replace('__SPEC__', () => specLiteral);
  return {
    language,
    path: appCliPath(normalized.name, language),
    content,
    mode: 0o755,
    sha256: crypto.createHash('sha256').update(content).digest('hex'),
    spec: normalized,
  };
}
