/**
 * Total Recall — Standalone Application Creator
 *
 * Implements Phase 3 of CAPABILITY_DEPLOYMENT_PLUGINS:
 * - Scaffolds clean-room runnable standalone application shell
 * - Initializes SSSS vault and project Total Recall brain
 * - Deploys initial capability plugin in isolated staging
 * - Verifies static gates before atomic publication to target directory
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { applyDeploymentPlan, resolveAppVaultDir, formatSsssDocument } from './apply.mjs';
import { createDeploymentPlan } from './plan.mjs';

export class AppCreateError extends Error {
  constructor(message, details = {}) {
    super(message);
    this.name = 'AppCreateError';
    this.details = details;
  }
}

/**
 * Copies a directory recursively from src to dest.
 * @param {string} src
 * @param {string} dest
 */
function copyDirSync(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const item of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, item.name);
    const destPath = path.join(dest, item.name);
    if (item.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * Scaffolds and publishes a new standalone application with an initial capability plugin.
 *
 * @param {string} targetDir - Destination directory for the new app
 * @param {object} options
 * @param {string} options.plugin - Source path or identifier for initial capability
 * @param {string} [options.adapter] - Target adapter (default: 'ssss-app')
 * @param {string} [options.name] - Application name
 * @param {boolean} [options.force] - Allow overwriting non-empty target directory
 * @param {boolean} [options.initBrain] - Initialize project Total Recall brain (default: true)
 * @param {boolean} [options.runGates] - Run pre-publish verification gates (default: true)
 * @returns {Promise<{
 *   success: boolean,
 *   targetDir: string,
 *   name: string,
 *   adapter: string,
 *   capabilities: string[],
 *   published_at: string
 * }>}
 */
export async function createStandaloneApp(targetDir, options = {}) {
  const resolvedTarget = path.resolve(targetDir);
  const appName = options.name || path.basename(resolvedTarget);
  const adapter = options.adapter || 'ssss-app';
  const initBrain = options.initBrain !== false;
  const runGates = options.runGates !== false;

  if (!options.plugin) {
    throw new AppCreateError('Missing required capability plugin source (--plugin)');
  }

  // Guard against accidental overwrite
  if (fs.existsSync(resolvedTarget) && !options.force) {
    const items = fs.readdirSync(resolvedTarget);
    if (items.length > 0) {
      throw new AppCreateError(
        `Target directory '${resolvedTarget}' is not empty. Use --force to overwrite.`
      );
    }
  }

  // 1. Staged creation in isolated directory
  const stagingDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tr-app-create-'));

  try {
    // 2. Scaffold standard SSSS application shell
    const packageJson = {
      name: appName,
      version: '0.1.0',
      type: 'module',
      scripts: {
        start: 'node index.mjs',
        check: 'node check.mjs'
      },
      ssss: {
        spec_version: '0.9.6',
        adapter
      }
    };
    fs.writeFileSync(
      path.join(stagingDir, 'package.json'),
      JSON.stringify(packageJson, null, 2),
      'utf8'
    );

    // Standalone entrypoint runnable without Total Recall daemon
    const indexJs = `/**
 * ${appName} — Standalone SSSS Application Entrypoint
 * Generated by Total Recall Capability Engine.
 * Operates independently with zero external database dependencies.
 */

import fs from 'node:fs';
import path from 'node:path';

export function getAppInfo() {
  return {
    name: '${appName}',
    adapter: '${adapter}',
    status: 'ready',
    vault: path.resolve('vault')
  };
}

if (import.meta.url === \`file://\${process.argv[1]}\`) {
  console.log('🚀 ${appName} started in standalone mode');
  console.log('📦 SSSS Adapter: ${adapter}');
  console.log('📁 Vault Root:  ', path.resolve('vault'));
}
`;
    fs.writeFileSync(path.join(stagingDir, 'index.mjs'), indexJs, 'utf8');

    // Standalone verification gate runner
    const checkJs = `/**
 * ${appName} — Verification Gate
 */
import fs from 'node:fs';
import path from 'node:path';

export function runChecks() {
  const vaultDir = path.resolve('vault');
  if (!fs.existsSync(vaultDir)) {
    throw new Error('Missing required SSSS vault directory');
  }
  return { passed: true, checks: ['vault_present', 'entrypoint_present'] };
}

if (import.meta.url === \`file://\${process.argv[1]}\`) {
  const result = runChecks();
  console.log('✔ All verification gates passed:', result.checks.join(', '));
}
`;
    fs.writeFileSync(path.join(stagingDir, 'check.mjs'), checkJs, 'utf8');

    // SSSS Vault structure
    const vaultDir = path.join(stagingDir, 'vault');
    fs.mkdirSync(path.join(vaultDir, 'system', 'capabilities'), { recursive: true });
    fs.mkdirSync(path.join(vaultDir, 'system', 'grants'), { recursive: true });
    fs.mkdirSync(path.join(vaultDir, 'system', 'events'), { recursive: true });

    // 3. Initialize project Total Recall brain if requested
    if (initBrain) {
      const brainDir = path.join(stagingDir, '.agent', 'skills', 'total-recall');
      fs.mkdirSync(path.join(brainDir, 'memory-vault'), { recursive: true });
      fs.mkdirSync(path.join(stagingDir, '.agent', 'commands'), { recursive: true });
    }

    // 4. Deploy initial capability plugin into staging
    const plan = await createDeploymentPlan(options.plugin, {
      target: stagingDir,
      adapter
    });

    if (!plan.valid) {
      throw new AppCreateError(
        `Capability plugin is invalid for target app: ${plan.conflicts?.length || 0} conflict(s)`
      );
    }

    const applied = await applyDeploymentPlan(plan, {
      target: stagingDir,
      actor: 'total-recall/app-create'
    });

    // Write standard README.md if capability did not supply one
    const readmePath = path.join(stagingDir, 'README.md');
    if (!fs.existsSync(readmePath)) {
      fs.writeFileSync(
        readmePath,
        `# ${appName}\n\nStandalone SSSS application powered by the Total Recall capability engine.\n`,
        'utf8'
      );
    }

    // 5. Verification Gates
    if (runGates) {
      if (!fs.existsSync(path.join(stagingDir, 'package.json'))) {
        throw new AppCreateError('Verification gate failed: package.json missing in staged app');
      }
      if (!fs.existsSync(path.join(stagingDir, 'index.mjs'))) {
        throw new AppCreateError('Verification gate failed: entrypoint index.mjs missing');
      }
      for (const capId of applied.capabilities) {
        const capRecord = path.join(stagingDir, 'vault', 'system', 'capabilities', `${capId}.md`);
        if (!fs.existsSync(capRecord)) {
          throw new AppCreateError(
            `Verification gate failed: capability installation record missing for '${capId}'`
          );
        }
      }
    }

    // 6. Atomic Publication to target directory
    if (fs.existsSync(resolvedTarget) && options.force) {
      fs.rmSync(resolvedTarget, { recursive: true, force: true });
    }

    fs.mkdirSync(path.dirname(resolvedTarget), { recursive: true });

    try {
      fs.renameSync(stagingDir, resolvedTarget);
    } catch {
      // Fallback if renaming crosses device boundaries
      copyDirSync(stagingDir, resolvedTarget);
      fs.rmSync(stagingDir, { recursive: true, force: true });
    }

    return {
      success: true,
      targetDir: resolvedTarget,
      name: appName,
      adapter,
      capabilities: applied.capabilities,
      published_at: new Date().toISOString()
    };
  } catch (err) {
    if (fs.existsSync(stagingDir)) {
      try {
        fs.rmSync(stagingDir, { recursive: true, force: true });
      } catch {}
    }
    throw new AppCreateError(`Failed to create standalone application: ${err.message}`, {
      error: err
    });
  }
}
