/**
 * inject.mjs — ACTIVE CONTEXT Injector (Total Recall Layer 5)
 *
 * Phase 11.5: ACTIVE CONTEXT is now ISOLATED in its own file
 * (~/.total-recall/active-context.md) instead of being spliced into
 * INSTRUCTIONS.md. This prevents concurrent write races between threads.
 *
 * Features:
 *   - Priority queue with 7-item cap (caution > important > tip > note)
 *   - Standalone file output (no system prompt modification)
 *   - SHA-256 content dedup to avoid injecting the same item twice
 *
 * The primary agent reads this file via the /start protocol or
 * co-processor injection into the system prompt's include chain.
 */

import fs from 'fs';
import path from 'path';
import { createHash } from 'crypto';
import os from 'os';

// ─── CONSTANTS ──────────────────────────────────────────────────────────────────

const PRIORITY_ORDER = ['caution', 'important', 'tip', 'note'];
const DEFAULT_MAX_ITEMS = 7;
const DEFAULT_ACTIVE_CONTEXT_PATH = path.join(os.homedir(), '.total-recall', 'active-context.md');

// ─── PRIORITY QUEUE ─────────────────────────────────────────────────────────────

/**
 * Sort and cap items by priority.
 * Priority: caution > important > tip > note.
 * Within same priority, newest items first (last added = highest).
 *
 * @param {Object[]} items - Context items with type field
 * @param {number} [maxItems=7] - Maximum items to keep
 * @returns {Object[]} Sorted and capped items
 */
export function prioritize(items, maxItems = DEFAULT_MAX_ITEMS) {
  const sorted = [...items].sort((a, b) => {
    const pa = PRIORITY_ORDER.indexOf(a.type);
    const pb = PRIORITY_ORDER.indexOf(b.type);
    // Lower index = higher priority
    const prioA = pa === -1 ? PRIORITY_ORDER.length : pa;
    const prioB = pb === -1 ? PRIORITY_ORDER.length : pb;
    return prioA - prioB;
  });
  return sorted.slice(0, maxItems);
}

// ─── DEDUPLICATION ──────────────────────────────────────────────────────────────

/**
 * Generate a content hash for deduplication.
 * @param {Object} item - Context item
 * @returns {string} SHA-256 hex hash (first 16 chars)
 */
function itemHash(item) {
  const content = `${item.type}:${item.label}:${item.text}`;
  return createHash('sha256').update(content).digest('hex').slice(0, 16);
}

/**
 * Deduplicate items by content hash.
 * @param {Object[]} items - Context items
 * @returns {Object[]} Deduplicated items
 */
export function deduplicate(items) {
  const seen = new Set();
  return items.filter(item => {
    const hash = itemHash(item);
    if (seen.has(hash)) return false;
    seen.add(hash);
    return true;
  });
}

// ─── WRITE ACTIVE CONTEXT ───────────────────────────────────────────────────────

/**
 * Write context items to the isolated active-context.md file.
 * This replaces the old approach of splicing into INSTRUCTIONS.md.
 *
 * @param {string} filePath - Path to active-context.md (default: ~/.total-recall/active-context.md)
 * @param {Object[]} items - Array of context items to inject
 * @param {string} items[].type - 'tip' | 'caution' | 'important' | 'note'
 * @param {string} items[].label - Short label (e.g., "Relevant Memory")
 * @param {string} items[].text - The context text to display
 * @param {Object} [options] - Options
 * @param {number} [options.maxItems=7] - Maximum items in the output
 * @param {boolean} [options.append=false] - If true, merge with existing items instead of replacing
 * @returns {{ success: boolean, error?: string, itemCount: number, dropped: number }}
 */
export function writeActiveContext(filePath, items, options = {}) {
  const { maxItems = DEFAULT_MAX_ITEMS, append = false } = options;
  const targetPath = filePath || DEFAULT_ACTIVE_CONTEXT_PATH;

  // Ensure parent directory exists
  const dir = path.dirname(targetPath);
  fs.mkdirSync(dir, { recursive: true });

  let allItems = [...items];

  // If append mode, merge with existing items
  if (append && fs.existsSync(targetPath)) {
    const existing = parseActiveContext(targetPath);
    allItems = [...existing, ...items];
  }

  // Deduplicate then prioritize
  const deduped = deduplicate(allItems);
  const prioritized = prioritize(deduped, maxItems);
  const dropped = deduped.length - prioritized.length;

  // Build the file content
  const timestamp = new Date().toISOString();
  const lines = [];
  lines.push('## ACTIVE CONTEXT');
  lines.push(`> Auto-generated by Memory Co-Processor. Do NOT edit manually.`);
  lines.push(`> Last refreshed: ${timestamp}`);
  lines.push('');

  for (const item of prioritized) {
    const alertType = item.type === 'tip' ? 'TIP'
      : item.type === 'caution' ? 'CAUTION'
      : item.type === 'important' ? 'IMPORTANT'
      : 'NOTE';
    lines.push(`> [!${alertType}]`);
    lines.push(`> **${item.label}**: ${item.text}`);
    lines.push('');
  }

  if (prioritized.length === 0) {
    lines.push('> No active context for current topic.');
    lines.push('');
  }

  fs.writeFileSync(targetPath, lines.join('\n'));

  return { success: true, itemCount: prioritized.length, dropped };
}

// ─── PARSE ACTIVE CONTEXT ───────────────────────────────────────────────────────

/**
 * Parse existing active-context.md back into structured items.
 * Used for append mode to merge with new items.
 *
 * @param {string} filePath - Path to active-context.md
 * @returns {Object[]} Parsed items
 */
export function parseActiveContext(filePath) {
  if (!fs.existsSync(filePath)) return [];

  const content = fs.readFileSync(filePath, 'utf-8');
  const items = [];
  const alertRegex = />\s*\[!(TIP|CAUTION|IMPORTANT|NOTE)\]\s*\n>\s*\*\*(.+?)\*\*:\s*(.+)/g;

  let match;
  while ((match = alertRegex.exec(content)) !== null) {
    items.push({
      type: match[1].toLowerCase(),
      label: match[2].trim(),
      text: match[3].trim(),
    });
  }

  return items;
}

// ─── CLEAR ACTIVE CONTEXT ───────────────────────────────────────────────────────

/**
 * Clear the active-context.md file.
 * Used during graceful shutdown of the co-processor.
 *
 * @param {string} [filePath] - Path to active-context.md
 * @returns {{ success: boolean }}
 */
export function clearActiveContext(filePath) {
  const targetPath = filePath || DEFAULT_ACTIVE_CONTEXT_PATH;

  if (!fs.existsSync(targetPath)) {
    return { success: true }; // Nothing to clear
  }

  try {
    fs.unlinkSync(targetPath);
    return { success: true };
  } catch {
    return { success: false };
  }
}

// ─── LEGACY COMPAT: WRITE TO SYSTEM PROMPT ──────────────────────────────────────

/**
 * DEPRECATED: Write ACTIVE CONTEXT directly into a system prompt file.
 * Kept for backward compatibility during migration. Use writeActiveContext() instead.
 *
 * @param {string} filePath - Path to system prompt file (e.g., INSTRUCTIONS.md)
 * @param {Object[]} items - Context items
 * @param {string} [sectionHeader='## ACTIVE CONTEXT'] - Section header
 * @returns {{ success: boolean, error?: string, itemCount: number }}
 */
export function writeActiveContextLegacy(filePath, items, sectionHeader = '## ACTIVE CONTEXT') {
  if (!fs.existsSync(filePath)) {
    return { success: false, error: `File not found: ${filePath}`, itemCount: 0 };
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const timestamp = new Date().toISOString();

  // Build the ACTIVE CONTEXT section
  const lines = [];
  lines.push(sectionHeader);
  lines.push(`> Auto-generated by Memory Co-Processor. Do NOT edit manually.`);
  lines.push(`> Last refreshed: ${timestamp}`);
  lines.push('');

  for (const item of items) {
    const alertType = item.type === 'tip' ? 'TIP'
      : item.type === 'caution' ? 'CAUTION'
      : item.type === 'important' ? 'IMPORTANT'
      : 'NOTE';
    lines.push(`> [!${alertType}]`);
    lines.push(`> **${item.label}**: ${item.text}`);
    lines.push('');
  }

  if (items.length === 0) {
    lines.push('> No active context for current topic.');
    lines.push('');
  }

  const section = lines.join('\n');

  // Find existing section or insert before DISTILLED MEMORY
  const sectionStart = content.indexOf(sectionHeader);

  if (sectionStart !== -1) {
    const afterHeader = content.indexOf('\n', sectionStart);
    const nextSection = content.indexOf('\n## ', afterHeader + 1);
    const sectionEnd = nextSection !== -1 ? nextSection : content.length;
    const newContent = content.slice(0, sectionStart) + section + content.slice(sectionEnd);
    fs.writeFileSync(filePath, newContent);
  } else {
    const distilledIdx = content.indexOf('## DISTILLED MEMORY');
    if (distilledIdx !== -1) {
      const newContent = content.slice(0, distilledIdx) + section + '\n' + content.slice(distilledIdx);
      fs.writeFileSync(filePath, newContent);
    } else {
      fs.appendFileSync(filePath, '\n' + section);
    }
  }

  return { success: true, itemCount: items.length };
}
