import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveAgentDir } from './agent-dir.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Resolve templates dir relative to this file (src/cli/ → ../../templates/)
const TEMPLATES_DIR = path.resolve(__dirname, '..', '..', 'templates');

const CLIENTS = {
  vscode: {
    label: 'VS Code Copilot',
    mode: 'file',
    writeMcpConfig: 'vscode',
    target: path.join('.github', 'copilot-instructions.md'),
    render: instructions => `<!-- Total Recall — auto-generated by \`npx total-recall connect vscode\` -->\n<!-- Do not edit; re-run connect to refresh -->\n\n${instructions}`
  },
  pi: {
    label: 'Pi Coding Agent',
    mode: 'global-symlink',
    writeMcpConfig: 'pi',
    globalTarget: path.join(os.homedir(), '.pi', 'agent', 'AGENTS.md'),
    localTarget: 'AGENTS.md',
  },
  hermes: {
    label: 'Hermes Agent',
    mode: 'hermes',
    writeMcpConfig: 'hermes',
    memoryPath: path.join(os.homedir(), '.hermes', 'memories', 'MEMORY.md'),
    userPath:   path.join(os.homedir(), '.hermes', 'memories', 'USER.md'),
  },
  openclaw: {
    label: 'OpenClaw',
    mode: 'openclaw',
    writeMcpConfig: 'openclaw',
    memoryTarget: 'MEMORY.md',
    agentsTarget: 'AGENTS.md',
  },
  cursor: {
    label: 'Cursor',
    mode: 'file',
    writeMcpConfig: 'cursor',
    target: path.join('.cursor', 'rules', 'total-recall.mdc'),
    render: instructions => [
      '---',
      'description: "Total Recall — Auto-generated behavioral memory surface."',
      'globs:',
      'alwaysApply: true',
      '---',
      '',
      instructions
    ].join('\n')
  },
  'claude-code': {
    label: 'Claude Code',
    mode: 'symlink',
    writeMcpConfig: 'claude-code',
    target: 'CLAUDE.md',
    writeSlashCommands: true
  },
  codex: {
    label: 'Codex',
    mode: 'symlink',
    writeMcpConfig: 'codex',
    target: 'AGENTS.md'
  },
  antigravity: {
    label: 'Antigravity',
    mode: 'symlink',
    writeMcpConfig: 'antigravity',
    target: 'AGENTS.md'
  },
  gemini: {
    label: 'Gemini',
    mode: 'symlink',
    writeMcpConfig: 'gemini',
    target: 'GEMINI.md'
  },
  windsurf: {
    label: 'Windsurf',
    mode: 'file',
    writeMcpConfig: 'windsurf',
    target: path.join('.windsurf', 'rules', 'total-recall.md'),
    render: instructions => instructions
  },
  aider: {
    label: 'Aider',
    mode: 'file',
    target: '.aider.rules.md',
    render: instructions => instructions,
    after: [
      'Add this to .aider.conf.yml:',
      '',
      'read:',
      '  - .aider.rules.md'
    ].join('\n')
  },
  ultrachat: {
    label: 'UltraChat',
    mode: 'api'
    // No file projection: UltraChat connects via the OpenAI-compatible API.
    // The compiled INSTRUCTIONS.md is injected per-request by the server.
    // See docs/guides/ultrachat.md for session sync via /api/sessions/*.
  },
  obsidian: {
    label: 'Obsidian',
    mode: 'vault',
    // Symlinks ~/.agent/memory-vault/ into the Obsidian vault as "Total Recall/"
    // Obsidian indexes all SSSS nodes natively — graph view, backlinks, search.
    folderName: 'Total Recall'
  },
  mcp: {
    label: 'MCP Client',
    mode: 'mcp',
    writeMcpConfig: 'generic'
  },
  generic: {
    label: 'Generic OpenAI-Compatible Client',
    mode: 'api',
    writeMcpConfig: 'generic'
  }
};

function parseArgs(args) {
  const opts = {
    client: args[0] && !args[0].startsWith('--') ? args[0] : null,
    brain: null,
    token: null,
    vault: null,
    force: false,
    json: false,
    help: false
  };

  for (let i = opts.client ? 1 : 0; i < args.length; i++) {
    switch (args[i]) {
      case '--brain': opts.brain = args[++i]; break;
      case '--token': opts.token = args[++i]; break;
      case '--vault': opts.vault = args[++i]; break;
      case '--force': opts.force = true; break;
      case '--json': opts.json = true; break;
      case '--help':
      case '-h':
        opts.help = true;
        break;
    }
  }

  return opts;
}

function printHelp() {
  console.log(`
  total-recall connect — Configure an IDE or external system

  Usage: total-recall connect <client> [options]

  Clients:
    cursor
    claude-code
    codex
    antigravity
    gemini
    windsurf
    aider
    ultrachat
    obsidian
    mcp
    generic

  Options:
    --brain <url>      Brain base URL for API/MCP clients
    --token <token>    Bearer PAT for generated snippets
    --vault <path>     Obsidian vault path (auto-detected on macOS if omitted)
    --force            Overwrite generated target files
    --json             Emit machine-readable connection details
    --help, -h         Show this help
`);
}

function readInstructions(cwd, agentDir) {
  const candidates = [
    path.join(cwd, 'INSTRUCTIONS.md'),
    path.join(agentDir, 'INSTRUCTIONS.md')
  ];
  const found = candidates.find(file => fs.existsSync(file));
  if (!found) return null;
  return fs.readFileSync(found, 'utf8');
}

function ensureBrainConfig(agentDir, opts) {
  if (!opts.brain) return null;
  const configDir = path.join(agentDir, 'config');
  fs.mkdirSync(configDir, { recursive: true });
  const config = { url: opts.brain };
  if (opts.token) config.token = opts.token;
  const filePath = path.join(configDir, 'brain.json');
  fs.writeFileSync(filePath, JSON.stringify(config, null, 2));
  return filePath;
}

function registerClient(agentDir, clientName, preset, projectionPath) {
  const configDir = path.join(agentDir, 'config');
  fs.mkdirSync(configDir, { recursive: true });
  const registryPath = path.join(configDir, 'clients.json');
  let registry = { clients: {} };
  if (fs.existsSync(registryPath)) {
    try { registry = JSON.parse(fs.readFileSync(registryPath, 'utf8')); }
    catch { /* corrupt file — start fresh */ }
  }
  registry.clients ??= {};
  registry.clients[clientName] = {
    label: preset.label,
    mode: preset.mode,
    projectionPath: projectionPath || null,
    connectedAt: new Date().toISOString()
  };
  fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2), 'utf8');
}

function writeFileProjection(cwd, preset, instructions, opts) {
  const targetPath = path.join(cwd, preset.target);
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  const existed = fs.existsSync(targetPath);
  if (fs.existsSync(targetPath) && !opts.force) {
    return { targetPath, action: 'exists' };
  }
  const content = preset.render(instructions);
  fs.writeFileSync(targetPath, content, 'utf8');
  return { targetPath, action: existed ? 'written' : 'created' };
}

function writeSymlinkProjection(cwd, preset, opts) {
  const instructionsPath = path.join(cwd, 'INSTRUCTIONS.md');
  if (!fs.existsSync(instructionsPath)) {
    throw new Error(`Cannot create ${preset.target}: ${instructionsPath} does not exist. Run npx total-recall init or compile first.`);
  }

  const targetPath = path.join(cwd, preset.target);
  if (fs.existsSync(targetPath)) {
    if (!opts.force) return { targetPath, action: 'exists' };
    fs.rmSync(targetPath, { force: true, recursive: true });
  }
  fs.symlinkSync('INSTRUCTIONS.md', targetPath);
  return { targetPath, action: 'symlinked' };
}

function apiDetails(opts) {
  const base = (opts.brain || 'http://127.0.0.1:3000').replace(/\/$/, '');
  return {
    base_url: base,
    chat_completions_url: `${base}/v1/chat/completions`,
    models_url: `${base}/v1/models`,
    mcp_url: `${base}/mcp`,
    ssss_manifest_url: `${base}/api/ssss`,
    discovery_url: `${base}/.well-known/total-recall.json`,
    authorization_header: opts.token ? `Authorization: Bearer ${opts.token}` : 'Authorization: Bearer <PAT>'
  };
}

function detectObsidianVault() {
  // macOS: Obsidian stores vault paths in its app support config
  const obsidianConfig = path.join(
    os.homedir(), 'Library', 'Application Support', 'obsidian', 'obsidian.json'
  );
  if (fs.existsSync(obsidianConfig)) {
    try {
      const cfg = JSON.parse(fs.readFileSync(obsidianConfig, 'utf8'));
      const vaults = Object.values(cfg.vaults || {});
      // Prefer the most recently opened vault
      const sorted = vaults.sort((a, b) => (b.ts || 0) - (a.ts || 0));
      if (sorted.length > 0 && sorted[0].path) return sorted[0].path;
    } catch { /* ignore parse errors */ }
  }
  // Linux: check common locations
  const xdgConfig = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
  const linuxConfig = path.join(xdgConfig, 'obsidian', 'obsidian.json');
  if (fs.existsSync(linuxConfig)) {
    try {
      const cfg = JSON.parse(fs.readFileSync(linuxConfig, 'utf8'));
      const vaults = Object.values(cfg.vaults || {});
      const sorted = vaults.sort((a, b) => (b.ts || 0) - (a.ts || 0));
      if (sorted.length > 0 && sorted[0].path) return sorted[0].path;
    } catch { /* ignore */ }
  }
  return null;
}

function writeVaultProjection(agentDir, preset, opts) {
  const vaultPath = opts.vault || detectObsidianVault();
  if (!vaultPath) {
    throw new Error(
      'Could not detect an Obsidian vault. Pass --vault <path> to specify one.\n' +
      '  e.g. total-recall connect obsidian --vault ~/Documents/MyVault'
    );
  }
  if (!fs.existsSync(vaultPath)) {
    throw new Error(`Obsidian vault not found: ${vaultPath}`);
  }

  const memoryVault = path.join(agentDir, 'memory-vault');
  if (!fs.existsSync(memoryVault)) {
    throw new Error(`Memory vault not found: ${memoryVault}. Run "total-recall init" first.`);
  }

  const linkPath = path.join(vaultPath, preset.folderName);
  const linkExists = fs.existsSync(linkPath) ||
    (() => { try { return fs.lstatSync(linkPath) && true; } catch { return false; } })();
  if (linkExists) {
    if (!opts.force) return { targetPath: linkPath, vaultPath, action: 'exists' };
    fs.rmSync(linkPath, { force: true, recursive: true });
  }
  fs.symlinkSync(memoryVault, linkPath);

  // Install Dataview query dashboard files into memory-vault/queries/
  // These are TR-native markdown files; Dataview renders them in Obsidian.
  const queriesTemplateDir = path.join(TEMPLATES_DIR, 'obsidian-queries');
  const queriesDestDir = path.join(memoryVault, 'queries');
  if (fs.existsSync(queriesTemplateDir)) {
    fs.mkdirSync(queriesDestDir, { recursive: true });
    for (const file of fs.readdirSync(queriesTemplateDir)) {
      const dest = path.join(queriesDestDir, file);
      if (!fs.existsSync(dest)) {
        fs.copyFileSync(path.join(queriesTemplateDir, file), dest);
      }
    }
  }

  return { targetPath: linkPath, vaultPath, action: 'symlinked' };
}

function printApiSnippet(client, details) {
  console.log(`\n  ${client.label} connection details\n`);
  console.log(`  Discovery: ${details.discovery_url}`);
  console.log(`  Models:    ${details.models_url}`);
  console.log(`  Chat:      ${details.chat_completions_url}`);
  console.log(`  MCP:       ${details.mcp_url}`);
  console.log(`  SSSS:      ${details.ssss_manifest_url}`);
  console.log(`  Auth:      ${details.authorization_header}`);
  console.log('\n  OpenAI-compatible config:');
  console.log(`    baseURL: ${details.base_url}/v1`);
  console.log('    model:   total-recall/gemma4');
}

function writeClaudeCodeSlashCommands(opts) {
  const commandsDir = path.join(os.homedir(), '.claude', 'commands');
  fs.mkdirSync(commandsDir, { recursive: true });

  const base = (opts.brain || 'http://127.0.0.1:3000').replace(/\/$/, '');
  const authHeader = opts.token ? `Authorization: Bearer ${opts.token}` : 'Authorization: Bearer <your-PAT>';

  const commands = [
    {
      file: 'memory.md',
      description: 'Search or manage Total Recall memory',
      body: `Search or manage your Total Recall memory via the REST API.

Brain URL: ${base}
Auth header: ${authHeader}

Usage examples (pass as arguments):
  search <query>     — semantic search across all memory nodes
  list               — list all nodes
  add <title> <body> — create a new memory node

Call \`${base}/api/memory/search\` with body \`{"query":"$ARGUMENTS"}\` to search.
Call \`${base}/api/memory\` with POST to add nodes.
Always include the Authorization header above.

$ARGUMENTS`
    },
    {
      file: 'brain.md',
      description: 'Show Total Recall brain status and health',
      body: `Check your Total Recall brain status.

Brain URL: ${base}
Auth header: ${authHeader}

Fetch \`${base}/health\` and \`${base}/api/health\` to check server health.
Fetch \`${base}/.well-known/total-recall.json\` for the full capability manifest.
Report: server status, model loaded, vault node count, connected clients.

$ARGUMENTS`
    },
    {
      file: 'vault.md',
      description: 'Compile or inspect Total Recall memory vault',
      body: `Compile or inspect the Total Recall SSSS memory vault.

Brain URL: ${base}
Auth header: ${authHeader}

Commands (pass as argument):
  compile            — POST ${base}/api/vault/compile  to rebuild INSTRUCTIONS.md
  nodes              — GET  ${base}/api/vault/nodes    to list all SSSS nodes
  surface            — GET  ${base}/api/vault/surface  to read compiled surface

$ARGUMENTS`
    },
    {
      file: 'recall.md',
      description: 'Ask Total Recall brain a question or run a task',
      body: `Send a message to your Total Recall brain.

Brain URL: ${base}
Auth header: ${authHeader}

POST to \`${base}/v1/chat/completions\` with:
  model: "total-recall"
  messages: [{"role":"user","content":"$ARGUMENTS"}]

Include the Authorization header. Stream the response if possible.

$ARGUMENTS`
    }
  ];

  const written = [];
  for (const cmd of commands) {
    const filePath = path.join(commandsDir, cmd.file);
    const content = `---\ndescription: "${cmd.description}"\n---\n${cmd.body}\n`;
    const existed = fs.existsSync(filePath);
    if (!existed || opts.force) {
      fs.writeFileSync(filePath, content, 'utf8');
      written.push({ file: cmd.file, action: existed ? 'updated' : 'created' });
    } else {
      written.push({ file: cmd.file, action: 'exists' });
    }
  }
  return written;
}

// ─── MCP Config Writers ──────────────────────────────────────────────────────
// Each IDE has a different config file location, format, and key structure.
// All writers merge with existing config (never clobber other MCP servers).
//
// opts.brain  — brain base URL, e.g. https://brain.example.com
// opts.token  — PAT, e.g. tr-abc123

function mergeJson(filePath, updateFn) {
  let current = {};
  if (fs.existsSync(filePath)) {
    try { current = JSON.parse(fs.readFileSync(filePath, 'utf8')); }
    catch { /* start fresh if corrupt */ }
  }
  const updated = updateFn(current);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(updated, null, 2), 'utf8');
  return filePath;
}

function mcpServerBlock(opts) {
  const base = (opts.brain || 'http://127.0.0.1:3000').replace(/\/$/, '');
  return {
    url: `${base}/mcp`,
    ...(opts.token ? { headers: { Authorization: `Bearer ${opts.token}` } } : {})
  };
}

function writeMcpConfigFor(ideKey, opts) {
  const home = os.homedir();
  const block = mcpServerBlock(opts);
  const serverEntry = { type: 'streamable-http', ...block };
  let configPath;

  switch (ideKey) {
    // ── Claude Code: ~/.claude.json (user-scope) + project .mcp.json ──────────
    // Format: { mcpServers: { "total-recall": { type, url, headers } } }
    case 'claude-code': {
      // User-scope (global): ~/.claude.json
      configPath = path.join(home, '.claude.json');
      mergeJson(configPath, cfg => {
        cfg.mcpServers ??= {};
        cfg.mcpServers['total-recall'] = serverEntry;
        return cfg;
      });
      // Project-scope: .mcp.json at cwd
      const projectMcp = path.join(process.cwd(), '.mcp.json');
      mergeJson(projectMcp, cfg => {
        cfg.mcpServers ??= {};
        cfg.mcpServers['total-recall'] = serverEntry;
        return cfg;
      });
      return [configPath, projectMcp];
    }

    // ── Cursor: ~/.cursor/mcp.json (global) ──────────────────────────────────
    // Format: { mcpServers: { "total-recall": { url, headers } } }
    // Note: Cursor does not use "type" field — url presence implies HTTP
    case 'cursor': {
      configPath = path.join(home, '.cursor', 'mcp.json');
      mergeJson(configPath, cfg => {
        cfg.mcpServers ??= {};
        cfg.mcpServers['total-recall'] = block; // no "type" field for Cursor
        return cfg;
      });
      return [configPath];
    }

    // ── VS Code: .vscode/mcp.json (workspace) ────────────────────────────────
    // Format: { servers: { "total-recall": { type: "http", url, headers } } }
    // Note: VS Code uses "servers" (not "mcpServers") and type: "http"
    case 'vscode': {
      configPath = path.join(process.cwd(), '.vscode', 'mcp.json');
      mergeJson(configPath, cfg => {
        cfg.servers ??= {};
        cfg.servers['total-recall'] = { type: 'http', ...block };
        return cfg;
      });
      return [configPath];
    }

    // ── Gemini CLI: ~/.gemini/settings.json ──────────────────────────────────
    // Format: { mcpServers: { "total-recall": { url } } }
    // Gemini CLI does not support headers in the documented config — use url only.
    // If token needed, user must pass via env var (TR_PAT) documented in note.
    case 'gemini': {
      configPath = path.join(home, '.gemini', 'settings.json');
      mergeJson(configPath, cfg => {
        cfg.mcpServers ??= {};
        // Gemini CLI: url only; headers not yet in stable spec
        cfg.mcpServers['total-recall'] = block;
        return cfg;
      });
      return [configPath];
    }

    // ── Windsurf: ~/.codeium/windsurf/mcp_config.json ────────────────────────
    // Format: { mcpServers: { "total-recall": { url } } }
    case 'windsurf': {
      configPath = path.join(home, '.codeium', 'windsurf', 'mcp_config.json');
      mergeJson(configPath, cfg => {
        cfg.mcpServers ??= {};
        cfg.mcpServers['total-recall'] = block;
        return cfg;
      });
      return [configPath];
    }

    // ── OpenAI Codex CLI: ~/.codex/config.toml ───────────────────────────────
    // Format: TOML  [mcp_servers.total-recall]  url = "..."  (no header support yet)
    // We write the TOML block by appending/replacing the section.
    case 'codex': {
      configPath = path.join(home, '.codex', 'config.toml');
      fs.mkdirSync(path.dirname(configPath), { recursive: true });
      let toml = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf8') : '';
      // Remove existing [mcp_servers.total-recall] block if present
      toml = toml.replace(/\[mcp_servers\.total-recall\][^\[]*/s, '').trimEnd();
      const base2 = (opts.brain || 'http://127.0.0.1:3000').replace(/\/$/, '');
      const newBlock = `\n\n[mcp_servers.total-recall]\nurl = "${base2}/mcp"\n`;
      fs.writeFileSync(configPath, toml + newBlock, 'utf8');
      return [configPath];
    }

    // ── Hermes: ~/.hermes/config.yaml ────────────────────────────────────────
    // Format: YAML  mcp_servers: {total-recall: {url, headers: {Authorization: ...}}}
    case 'hermes': {
      configPath = path.join(home, '.hermes', 'config.yaml');
      fs.mkdirSync(path.dirname(configPath), { recursive: true });
      let yaml = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf8') : '';
      // Remove existing total-recall block if present (simple line-based removal)
      yaml = yaml.replace(/  total-recall:[\s\S]*?(?=\n  \S|$)/m, '').trimEnd();
      const base3 = (opts.brain || 'http://127.0.0.1:3000').replace(/\/$/, '');
      let block3 = `\n  total-recall:\n    url: "${base3}/mcp"\n`;
      if (opts.token) block3 += `    headers:\n      Authorization: "Bearer ${opts.token}"\n`;
      if (!yaml.includes('mcp_servers:')) yaml += '\nmcp_servers:';
      // Insert after mcp_servers:
      yaml = yaml.replace('mcp_servers:', 'mcp_servers:' + block3);
      fs.writeFileSync(configPath, yaml.trim() + '\n', 'utf8');
      return [configPath];
    }

    // ── OpenClaw: ~/.openclaw/openclaw.json ───────────────────────────────────
    // Format: { mcp: { servers: { "total-recall": { url, transport, headers } } } }
    case 'openclaw': {
      configPath = path.join(home, '.openclaw', 'openclaw.json');
      mergeJson(configPath, cfg => {
        cfg.mcp ??= {};
        cfg.mcp.servers ??= {};
        cfg.mcp.servers['total-recall'] = {
          url: block.url,
          transport: 'streamable-http',
          ...(opts.token ? { headers: { Authorization: `Bearer ${opts.token}` } } : {})
        };
        return cfg;
      });
      return [configPath];
    }

    // ── Pi Coding Agent: ~/.pi/agent/settings.json ───────────────────────────
    // Format: { mcp: { "total-recall": { type, url, headers } } }
    case 'pi': {
      configPath = path.join(home, '.pi', 'agent', 'settings.json');
      mergeJson(configPath, cfg => {
        cfg.mcp ??= {};
        cfg.mcp['total-recall'] = serverEntry;
        return cfg;
      });
      return [configPath];
    }

    // ── Antigravity: .mcp.json at cwd (same format as Claude Code project scope)
    case 'antigravity': {
      configPath = path.join(process.cwd(), '.mcp.json');
      mergeJson(configPath, cfg => {
        cfg.mcpServers ??= {};
        cfg.mcpServers['total-recall'] = serverEntry;
        return cfg;
      });
      return [configPath];
    }

    // ── Generic: print JSON snippet only, no file written ────────────────────
    default: {
      return [];
    }
  }
}


export default async function connect(args) {
  const opts = parseArgs(args);
  if (opts.help || !opts.client) {
    printHelp();
    return;
  }

  const preset = CLIENTS[opts.client];
  if (!preset) {
    console.error(`Unknown client: ${opts.client}`);
    console.error(`Supported clients: ${Object.keys(CLIENTS).join(', ')}`);
    process.exit(1);
  }

  const cwd = process.cwd();
  const agentDir = process.env.AGENT_DIR || resolveAgentDir();
  const brainConfigPath = ensureBrainConfig(agentDir, opts);
  const details = apiDetails(opts);
  const result = {
    client: opts.client,
    label: preset.label,
    mode: preset.mode,
    brain_config_path: brainConfigPath,
    api: details,
    projection: null,
    notes: []
  };

  if (preset.mode === 'file') {
    const instructions = readInstructions(cwd, agentDir);
    if (!instructions) {
      throw new Error('No INSTRUCTIONS.md found. Run npx total-recall init or compile before connecting file-based IDEs.');
    }
    result.projection = writeFileProjection(cwd, preset, instructions, opts);
  } else if (preset.mode === 'symlink') {
    result.projection = writeSymlinkProjection(cwd, preset, opts);
  } else if (preset.mode === 'global-symlink') {
    // Pi: symlink ~/.pi/agent/AGENTS.md → compiled INSTRUCTIONS.md
    const instructionsPath = path.join(cwd, 'INSTRUCTIONS.md');
    if (!fs.existsSync(instructionsPath)) {
      throw new Error(`No INSTRUCTIONS.md found. Run npx total-recall init or compile first.`);
    }
    const targetPath = preset.globalTarget;
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    if (fs.existsSync(targetPath) || (() => { try { return fs.lstatSync(targetPath) && true; } catch { return false; } })()) {
      if (!opts.force) {
        result.projection = { targetPath, action: 'exists' };
      } else {
        fs.rmSync(targetPath, { force: true });
        fs.symlinkSync(instructionsPath, targetPath);
        result.projection = { targetPath, action: 'symlinked' };
      }
    } else {
      fs.symlinkSync(instructionsPath, targetPath);
      result.projection = { targetPath, action: 'symlinked' };
    }
    result.notes.push(`  ~/.pi/agent/AGENTS.md → ${instructionsPath}`);
  } else if (preset.mode === 'hermes') {
    // Hermes: write compiled MEMORY.md to ~/.hermes/memories/MEMORY.md (max 2200 chars)
    const instructions = readInstructions(cwd, agentDir);
    if (!instructions) throw new Error('No INSTRUCTIONS.md found. Run npx total-recall init or compile first.');
    fs.mkdirSync(path.dirname(preset.memoryPath), { recursive: true });
    const capped = instructions.slice(0, 2200);
    fs.writeFileSync(preset.memoryPath, capped, 'utf8');
    result.projection = { targetPath: preset.memoryPath, action: 'written' };
    result.notes.push(`  Hermes MEMORY.md (${capped.length} chars) → ${preset.memoryPath}`);
    result.notes.push('  Note: Hermes has a 2,200-char limit on MEMORY.md. Total Recall auto-caps this.');
  } else if (preset.mode === 'openclaw') {
    // OpenClaw: write MEMORY.md + symlink AGENTS.md in cwd
    const instructions = readInstructions(cwd, agentDir);
    if (!instructions) throw new Error('No INSTRUCTIONS.md found. Run npx total-recall init or compile first.');
    // MEMORY.md — curated facts extracted from instructions
    const memPath = path.join(cwd, preset.memoryTarget);
    if (!fs.existsSync(memPath) || opts.force) {
      fs.writeFileSync(memPath, instructions, 'utf8');
    }
    // AGENTS.md — symlink to INSTRUCTIONS.md
    const agentsPath = path.join(cwd, preset.agentsTarget);
    if (fs.existsSync(agentsPath) || (() => { try { return fs.lstatSync(agentsPath) && true; } catch { return false; } })()) {
      if (opts.force) { fs.rmSync(agentsPath, { force: true }); fs.symlinkSync('INSTRUCTIONS.md', agentsPath); }
    } else {
      fs.symlinkSync('INSTRUCTIONS.md', agentsPath);
    }
    result.projection = { targetPath: memPath, action: 'written' };
    result.notes.push(`  OpenClaw MEMORY.md written to ${memPath}`);
    result.notes.push(`  OpenClaw AGENTS.md → INSTRUCTIONS.md`);
  } else if (preset.mode === 'vault') {
    result.projection = writeVaultProjection(agentDir, preset, opts);
    result.notes.push([
      `  Vault linked: ${result.projection.vaultPath}/${preset.folderName}/`,
      `  → ${path.join(agentDir, 'memory-vault')}`,
      '',
      `  Open Obsidian and look for the "${preset.folderName}" folder.`,
      '  All SSSS memory nodes are visible in Graph View, Search, and Backlinks.',
      '',
      '  To back up via Obsidian Sync or iCloud, enable sync in Obsidian — the',
      `  symlinked folder will be included automatically.`
    ].join('\n'));
  }

  if (preset.after) result.notes.push(preset.after);

  // Write Claude Code slash commands for REST API access
  if (preset.writeSlashCommands) {
    const slashResults = writeClaudeCodeSlashCommands(opts);
    result.slash_commands = slashResults;
    const created = slashResults.filter(r => r.action !== 'exists');
    if (created.length > 0) {
      result.notes.push(`  Slash commands written to ~/.claude/commands/:\n` +
        created.map(r => `    /${r.file.replace('.md', '')} (${r.action})`).join('\n'));
    }
  }

  // Write MCP config for this IDE
  if (preset.writeMcpConfig) {
    try {
      const written = writeMcpConfigFor(preset.writeMcpConfig, opts);
      result.mcp_configs = written;
      if (written.length > 0) {
        result.notes.push(
          `  MCP config written:\n` +
          written.map(f => `    ${f}`).join('\n') +
          (opts.token ? '' : '\n\n  ⚠️  No PAT provided — MCP connection will be unauthenticated.\n     Pass --token <tr-...> or re-run after generating a PAT.')
        );
      }
    } catch (e) {
      result.notes.push(`  ⚠️  MCP config write failed: ${e.message}`);
    }
  }

  // Record this client in the registry so `status` can report freshness
  registerClient(agentDir, opts.client, preset, result.projection?.targetPath || null);

  if (opts.json) {
    console.log(JSON.stringify(result, null, 2));
    return;
  }

  console.log(`\n  Total Recall connected: ${preset.label}`);
  if (result.projection) {
    const action = result.projection.action;
    const target = result.projection.targetPath;
    const display = preset.mode === 'vault' ? target : path.relative(cwd, target);
    console.log(`  Projection: ${action} ${display}`);
  }
  if (brainConfigPath) {
    console.log(`  Brain config: ${brainConfigPath}`);
  }
  if (preset.mode !== 'vault') {
    printApiSnippet(preset, details);
  }
  for (const note of result.notes) {
    console.log(`\n${note}`);
  }
  console.log();
}
