/**
 * CLI for a layered skill's repo-layer config. Shared by
 * `total-recall skill config <id> …` and the per-skill command generated by
 * `total-recall command create <name> --config-for-skill <id>`.
 *
 * Exit codes: 0 ok · 1 runtime failure (missing skill/contract, I/O) ·
 * 2 usage or validation error.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createInterface } from 'node:readline/promises';
import {
  SkillConfigError,
  resolveSkillDir,
  loadConfigSchema,
  validateSkillConfig,
  readSkillConfig,
  readSkillConfigState,
  projectSkillConfig,
  recordPath,
  writeSkillConfig,
  getConfigValue,
  setConfigValue,
  parseCliValue,
  listCollections,
  parseCollectionItem,
  addCollectionItem,
  removeCollectionItem,
  detectSkillConfig,
  missingRequired,
} from '../core/skill-config.mjs';

function usage(prefix, collections) {
  const nouns = Object.entries(collections)
    .map(([noun, c]) => `    ${prefix} ${noun} list|add|remove        Manage '${c.property}' (key: ${c.key})`)
    .join('\n');
  return `Usage:
    ${prefix} config get [path]               Print the repo config or one value
    ${prefix} config set <path> <value>       Set a value (JSON or plain string), validated
    ${prefix} config unset <path>             Remove a value, validated
    ${prefix} config validate                 Check the record against the contract and config.json for drift
    ${prefix} config rebuild                  Regenerate config.json from the SSSS record
    ${prefix} config import                   Record an existing config.json (adoption)
    ${prefix} config schema                   Print core/config.schema.json
${nouns ? `${nouns}\n` : ''}    ${prefix} detect [--apply] [--force]       Propose a config from the repo (core/detect.mjs)
    ${prefix} init [--yes] [--force]           Create config.json from defaults, detection and prompts

  Options: --json (structured output) · --repo <path> (with 'skill config')`;
}

function topLevelDefaults(schema) {
  const defaults = {};
  for (const [key, definition] of Object.entries(schema.properties || {})) {
    if (definition && Object.hasOwn(definition, 'default')) defaults[key] = structuredClone(definition.default);
  }
  return defaults;
}

async function promptMissing(schema, config, keys) {
  const rl = createInterface({ input: process.stdin, output: process.stderr });
  try {
    let next = config;
    for (const key of keys) {
      const definition = schema.properties?.[key] || {};
      const hint = definition.enum ? ` (${definition.enum.join('|')})` : definition.type ? ` (${definition.type})` : '';
      const label = definition.description ? `${key} — ${definition.description}` : key;
      const answer = (await rl.question(`${label}${hint}: `)).trim();
      if (!answer) throw new SkillConfigError(`'${key}' is required`);
      next = setConfigValue(next, key, parseCliValue(answer));
    }
    return next;
  } finally {
    rl.close();
  }
}

/**
 * @param {string} skillId
 * @param {string[]} args   verb and arguments, e.g. ['config', 'set', 'tier', 'fast']
 * @param {{ repoRoot: string, prefix?: string }} opts
 */
export async function runSkillConfig(skillId, args, { repoRoot, prefix = `total-recall skill config ${skillId}` } = {}) {
  const json = args.includes('--json');
  const flags = new Set(args.filter((arg) => arg.startsWith('--')));
  const positional = args.filter((arg) => !arg.startsWith('--'));
  const out = (payload, text) => {
    if (json) console.log(JSON.stringify({ ok: true, ...payload }));
    else if (text !== undefined) console.log(text);
    return { ok: true, ...payload };
  };

  try {
    const skillDir = resolveSkillDir(repoRoot, skillId);
    const contract = loadConfigSchema(skillDir);
    const collections = listCollections(contract.schema);
    const [verb, action, ...rest] = positional;

    if (!verb || verb === 'help' || flags.has('--help')) {
      console.log(usage(prefix, collections));
      return { ok: true };
    }

    if (verb === 'config') {
      const state = readSkillConfigState(skillDir);
      const current = state.config;
      if (action === 'schema') return out({ schema: contract.schema }, JSON.stringify(contract.schema, null, 2));
      if (action === 'validate') {
        if (current === null) throw new SkillConfigError('No config yet; run init or detect --apply', { exitCode: 1 });
        const result = validateSkillConfig(contract, current);
        if (!result.valid) throw new SkillConfigError(`${state.source === 'record' ? recordPath(skillId) : 'config.json'} is invalid:\n  ${result.errors.join('\n  ')}`, { issues: result.errors });
        if (state.source !== 'record') throw new SkillConfigError(`config.json is valid but not recorded in SSSS; run '${prefix} config import'`, { exitCode: 1 });
        if (!state.inSync) throw new SkillConfigError(`config.json has drifted from ${recordPath(skillId)}; run '${prefix} config rebuild'`, { exitCode: 1 });
        return out({ valid: true, in_sync: true }, `${recordPath(skillId)} satisfies core/config.schema.json and config.json matches it`);
      }
      if (action === 'rebuild') {
        if (state.source !== 'record') throw new SkillConfigError(`No ${recordPath(skillId)} record to rebuild from`, { exitCode: 1 });
        projectSkillConfig(skillDir, state.record.config);
        return out({ config: state.record.config }, '✔ Rebuilt config.json from the SSSS record');
      }
      if (action === 'import') {
        if (state.source === 'record') return out({ config: current, imported: false }, `Already recorded at ${recordPath(skillId)}`);
        if (state.projection === null) throw new SkillConfigError('No config.json to import', { exitCode: 1 });
        const written = await writeSkillConfig(skillDir, contract, state.projection);
        return out({ config: written, imported: true }, `✔ Recorded config.json at ${recordPath(skillId)}`);
      }
      if (action === 'get') {
        const value = rest[0] ? getConfigValue(current ?? {}, rest[0]) : current;
        if (rest[0] && value === undefined) throw new SkillConfigError(`No value at '${rest[0]}'`, { exitCode: 1 });
        return out({ value: value ?? null }, typeof value === 'string' ? value : JSON.stringify(value ?? null, null, 2));
      }
      if (action === 'set' || action === 'unset') {
        if (!rest[0] || (action === 'set' && rest.length < 2)) throw new SkillConfigError(`Usage: ${prefix} config ${action} <path>${action === 'set' ? ' <value>' : ''}`);
        if (current === null) throw new SkillConfigError('No config.json yet; run init or detect --apply first', { exitCode: 1 });
        const value = action === 'set' ? parseCliValue(rest.slice(1).join(' ')) : undefined;
        const written = await writeSkillConfig(skillDir, contract, setConfigValue(current, rest[0], value));
        return out({ config: written }, `✔ ${action === 'set' ? 'Set' : 'Removed'} ${rest[0]}`);
      }
      throw new SkillConfigError(`Unknown config action '${action ?? ''}'\n${usage(prefix, collections)}`);
    }

    if (Object.hasOwn(collections, verb)) {
      const collection = collections[verb];
      const current = readSkillConfig(skillDir);
      if (action === 'list') {
        const items = getConfigValue(current ?? {}, collection.property) ?? [];
        return out({ items }, items.length ? items.map((item) => `- ${item?.[collection.key]}: ${JSON.stringify(item)}`).join('\n') : `No ${collection.property}.`);
      }
      if (current === null) throw new SkillConfigError('No config.json yet; run init or detect --apply first', { exitCode: 1 });
      if (action === 'add') {
        const item = parseCollectionItem(rest);
        const written = await writeSkillConfig(skillDir, contract, addCollectionItem(current, collection, item));
        return out({ config: written }, `✔ Added ${verb} '${item[collection.key]}'`);
      }
      if (action === 'remove') {
        if (!rest[0]) throw new SkillConfigError(`Usage: ${prefix} ${verb} remove <${collection.key}>`);
        const written = await writeSkillConfig(skillDir, contract, removeCollectionItem(current, collection, rest[0]));
        return out({ config: written }, `✔ Removed ${verb} '${rest[0]}'`);
      }
      throw new SkillConfigError(`Usage: ${prefix} ${verb} list|add|remove`);
    }

    if (verb === 'detect') {
      const proposal = await detectSkillConfig(skillDir, repoRoot);
      const checked = validateSkillConfig(contract, proposal);
      if (!flags.has('--apply')) {
        return out({ proposal, valid: checked.valid, errors: checked.errors },
          `${JSON.stringify(proposal, null, 2)}\n${checked.valid ? 'Valid. Re-run with --apply to write config.json.' : `Invalid:\n  ${checked.errors.join('\n  ')}`}`);
      }
      if (readSkillConfig(skillDir) !== null && !flags.has('--force')) {
        throw new SkillConfigError('A config already exists; use --force to replace it with the detected config', { exitCode: 1 });
      }
      const written = await writeSkillConfig(skillDir, contract, proposal);
      return out({ config: written }, '✔ Recorded the detected config and wrote config.json');
    }

    if (verb === 'init') {
      if (readSkillConfig(skillDir) !== null && !flags.has('--force')) {
        throw new SkillConfigError(`A config already exists; change it with '${prefix} config set' or pass --force`, { exitCode: 1 });
      }
      let config = topLevelDefaults(contract.schema);
      if (fs.existsSync(path.join(skillDir, 'core', 'detect.mjs'))) config = { ...config, ...(await detectSkillConfig(skillDir, repoRoot)) };
      const missing = missingRequired(contract.schema, config);
      if (missing.length) {
        if (flags.has('--yes') || json || !process.stdin.isTTY) {
          throw new SkillConfigError(`Missing required fields: ${missing.join(', ')}. Run interactively or set them after 'detect --apply'.`);
        }
        config = await promptMissing(contract.schema, config, missing);
      }
      const written = await writeSkillConfig(skillDir, contract, config);
      return out({ config: written }, `✔ Initialized ${path.relative(process.cwd(), path.join(skillDir, 'config.json')) || 'config.json'}`);
    }

    throw new SkillConfigError(`Unknown subcommand '${verb}'\n${usage(prefix, collections)}`);
  } catch (error) {
    const exitCode = Number.isInteger(error?.exitCode) ? error.exitCode : 1;
    if (json) console.log(JSON.stringify({ ok: false, exit_code: exitCode, error: error.message, ...(error.issues?.length ? { issues: error.issues } : {}) }));
    else console.error(`Error: ${error.message}`);
    process.exitCode = exitCode;
    return { ok: false, exit_code: exitCode, error: error.message };
  }
}
