version: '3.7'

services:
  headscale:
    image: headscale/headscale:0.22.3
    container_name: headscale
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "9091:9090"
    volumes:
      - ./config.yaml:/etc/headscale/config.yaml
      - ./data:/var/lib/headscale
    command: headscale serve
