#!/usr/bin/env node
/**
 * sync-prompts.mjs — Total Recall System Prompt Compatibility Layer
 *
 * Auto-detects which IDEs are in use in the current repo and syncs
 * the behavioral surface (DISTILLED MEMORY) to their rule files.
 *
 * Strategies per IDE:
 *   - Symlink:   Best for IDEs that support file refs (Antigravity, Claude Code)
 *   - Copy:      For IDEs that need their own format (Cursor, Windsurf, Roo, Continue)
 *   - Append:    For IDEs that merge multiple rule files
 *
 * Usage:
 *   total-recall sync-prompts              # Auto-detect and sync
 *   total-recall sync-prompts --list       # List detected IDEs
 *   total-recall sync-prompts --dry-run    # Preview without writing
 */

import fs from 'fs';
import path from 'path';

// ─── IDE RULE FILE DEFINITIONS ──────────────────────────────────────────────────

const IDE_CONFIGS = {
  antigravity: {
    label: 'Antigravity (Gemini)',
    detect: ['AGENTS.md', '.gemini/settings.json'],
    targets: ['INSTRUCTIONS.md'],
    strategy: 'symlink-or-section',
    description: 'Primary INSTRUCTIONS.md — behavioral surface injected directly',
  },
  'claude-code': {
    label: 'Claude Code',
    detect: ['CLAUDE.md', '.claude/settings.json'],
    targets: ['CLAUDE.md'],
    strategy: 'symlink-or-section',
    description: 'CLAUDE.md — symlinked to INSTRUCTIONS.md or section-injected',
  },
  cursor: {
    label: 'Cursor',
    detect: ['.cursor', '.cursor/rules', '.cursorrules'],
    targets: ['.cursor/rules/total-recall.mdc'],
    strategy: 'mdc-file',
    description: 'MDC rule file in .cursor/rules/',
    format: 'mdc',
  },
  windsurf: {
    label: 'Windsurf',
    detect: ['.windsurf', '.windsurfrules'],
    targets: ['.windsurf/rules/total-recall.md'],
    strategy: 'section-file',
    description: 'Rule file in .windsurf/rules/',
  },
  'roo-code': {
    label: 'Roo Code',
    detect: ['.roo', '.roorules', '.roo/rules'],
    targets: ['.roo/rules/total-recall.md'],
    strategy: 'section-file',
    description: 'Rule file in .roo/rules/',
  },
  'continue-dev': {
    label: 'Continue',
    detect: ['.continue', '.continue/rules'],
    targets: ['.continue/rules/total-recall.md'],
    strategy: 'section-file',
    description: 'Rule file in .continue/rules/',
  },
};

// ─── DETECT IDEs ────────────────────────────────────────────────────────────────

function detectIDEs(root, appConfig = null) {
  const detected = [];

  for (const [id, config] of Object.entries(IDE_CONFIGS)) {
    const found = config.detect.some(marker => {
      const markerPath = path.join(root, marker);
      return fs.existsSync(markerPath);
    });
    if (found) {
      const clonedIde = { id, ...config };
      // Agnostic override: If user config provides systemPromptFiles, dynamically override targets
      if (appConfig && appConfig.systemPromptFiles && clonedIde.strategy === 'symlink-or-section') {
        clonedIde.targets = appConfig.systemPromptFiles;
      }
      detected.push(clonedIde);
    }
  }

  return detected;
}

// ─── FORMAT BEHAVIORAL SURFACE FOR IDE ──────────────────────────────────────────

/**
 * Wrap the behavioral surface in an MDC (Markdown Context) file for Cursor.
 * MDC format uses YAML frontmatter with special fields.
 */
function formatAsMDC(surface) {
  return `---
description: "Total Recall — Auto-generated behavioral memory surface for this codebase."
globs:
alwaysApply: true
---

# Total Recall — Behavioral Memory

> This file is auto-generated by \`total-recall sync-prompts\`. Do not edit manually.
> Re-generate: \`total-recall sync-prompts\`

${surface}
`;
}

/**
 * Wrap the behavioral surface in a standalone rule file for IDEs
 * that support plain markdown rules (Windsurf, Roo, Continue).
 */
function formatAsRuleFile(surface) {
  return `# Total Recall — Behavioral Memory

> This file is auto-generated by \`total-recall sync-prompts\`. Do not edit manually.
> Re-generate: \`total-recall sync-prompts\`

${surface}
`;
}

// ─── SYNC SURFACE TO IDE ────────────────────────────────────────────────────────

async function syncToIDE(root, ide, surface, { dryRun = false } = {}) {
  const results = [];

  for (const target of ide.targets) {
    const targetPath = path.join(root, target);
    const targetDir = path.dirname(targetPath);

    if (ide.strategy === 'symlink-or-section') {
      // For INSTRUCTIONS.md and CLAUDE.md — inject section in-place
      if (fs.existsSync(targetPath)) {
        // Check if it's a symlink — if so, the surface is already shared
        if (fs.lstatSync(targetPath).isSymbolicLink()) {
          results.push({ target, status: 'symlink', detail: 'Shared via symlink — no separate injection needed' });
          continue;
        }
        // Inject the section
        if (dryRun) {
          results.push({ target, status: 'dry-run', detail: 'Would inject section' });
        } else {
          const { writeSurface } = await import('./surface.mjs');
          const result = writeSurface(targetPath, surface);
          results.push({ target, status: result.success ? 'injected' : 'error', detail: result.error || 'Section replaced' });
        }
      } else {
        results.push({ target, status: 'skip', detail: 'File not found' });
      }
    } else if (ide.strategy === 'mdc-file') {
      // Write MDC format file
      if (dryRun) {
        results.push({ target, status: 'dry-run', detail: `Would write MDC file (${formatAsMDC(surface).length} chars)` });
      } else {
        fs.mkdirSync(targetDir, { recursive: true });
        fs.writeFileSync(targetPath, formatAsMDC(surface));
        results.push({ target, status: 'written', detail: 'MDC rule file created' });
      }
    } else if (ide.strategy === 'section-file') {
      // Write plain markdown rule file
      if (dryRun) {
        results.push({ target, status: 'dry-run', detail: `Would write rule file (${formatAsRuleFile(surface).length} chars)` });
      } else {
        fs.mkdirSync(targetDir, { recursive: true });
        fs.writeFileSync(targetPath, formatAsRuleFile(surface));
        results.push({ target, status: 'written', detail: 'Rule file created' });
      }
    }
  }

  return results;
}

// ─── UNSYNC SURFACE FROM IDE ──────────────────────────────────────────────────────

export async function unsyncFromIDE(root, ide, { dryRun = false } = {}) {
  const results = [];

  for (const target of ide.targets) {
    const targetPath = path.join(root, target);

    if (ide.strategy === 'symlink-or-section') {
      if (fs.existsSync(targetPath)) {
        if (fs.lstatSync(targetPath).isSymbolicLink()) {
          results.push({ target, status: 'skip', detail: 'Is a symlink — leaving alone' });
          continue;
        }
        if (dryRun) {
          results.push({ target, status: 'dry-run', detail: 'Would clear section' });
        } else {
          const { clearSurface } = await import('./surface.mjs');
          const result = clearSurface(targetPath);
          results.push({ target, status: result.success ? 'cleared' : 'error', detail: result.error || 'Section removed' });
        }
      } else {
        results.push({ target, status: 'skip', detail: 'File not found' });
      }
    } else if (ide.strategy === 'mdc-file' || ide.strategy === 'section-file') {
      if (fs.existsSync(targetPath)) {
        if (dryRun) {
          results.push({ target, status: 'dry-run', detail: 'Would delete file' });
        } else {
          fs.unlinkSync(targetPath);
          results.push({ target, status: 'deleted', detail: 'File removed' });
        }
      } else {
        results.push({ target, status: 'skip', detail: 'File not found' });
      }
    }
  }

  return results;
}

// ─── MAIN ───────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2);
  const listOnly = args.includes('--list');
  const dryRun = args.includes('--dry-run');
  const unsync = args.includes('--unsync');

  // Resolve root
  let root = process.cwd();
  const rootIdx = args.indexOf('--root');
  if (rootIdx !== -1 && args[rootIdx + 1]) {
    root = path.resolve(args[rootIdx + 1]);
  }

  // Load config and paths early to support agnostic dynamic target injection
  const { loadConfig, resolvePaths } = await import('./utils.mjs');
  const config = await loadConfig(root);
  const paths = resolvePaths(root, config);

  // Detect IDEs
  const ides = detectIDEs(root, config);

  if (listOnly) {
    console.log(`\n🔍 Detected IDEs in ${root}:\n`);
    if (ides.length === 0) {
      console.log('  (none detected)\n');
    } else {
      for (const ide of ides) {
        console.log(`  🟢 ${ide.label} — ${ide.description}`);
        for (const target of ide.targets) {
          console.log(`     → ${target}`);
        }
      }
      console.log('');
    }

    // Also show undetected IDEs
    const undetected = Object.entries(IDE_CONFIGS).filter(([id]) => !ides.some(i => i.id === id));
    if (undetected.length > 0) {
      console.log('  Not detected:');
      for (const [id, config] of undetected) {
        console.log(`  ⚪ ${config.label} (create ${config.detect[0]} to enable)`);
      }
      console.log('');
    }
    return;
  }

  let result = null;
  if (!unsync) {
    const { compileSurface } = await import('./surface.mjs');
    result = compileSurface({
      wikiDir: paths.wikiDir,
      root,
      ranking: config.ranking,
    });

    if (!result) {
      console.log('📭 No wiki nodes found. Run `total-recall init` first.\n');
      return;
    }
  }

  console.log(`\n🧠 Total Recall — ${unsync ? 'Unsync' : 'Sync'} Prompts${dryRun ? ' (DRY RUN)' : ''}\n`);
  if (!unsync && result) {
    console.log(`   Surface: ${result.stats.totalNodes} nodes → ${result.stats.negativeRules} negative, ${result.stats.positiveRules} positive, ${result.stats.correctiveRules} corrective\n`);
  }

  if (ides.length === 0) {
    console.log('⚠️  No IDEs detected. Create one of these markers to enable:');
    for (const [id, config] of Object.entries(IDE_CONFIGS)) {
      console.log(`   - ${config.detect[0]} → ${config.label}`);
    }
    console.log('');
    return;
  }

  for (const ide of ides) {
    console.log(`  📺 ${ide.label}:`);
    const syncResults = unsync 
      ? await unsyncFromIDE(root, ide, { dryRun })
      : await syncToIDE(root, ide, result.surface, { dryRun });
      
    for (const r of syncResults) {
      const icon = r.status === 'written' || r.status === 'injected' ? '✅' :
                   r.status === 'cleared' || r.status === 'deleted' ? '🗑️' :
                   r.status === 'symlink' ? '🔗' :
                   r.status === 'dry-run' ? '🏜️' :
                   r.status === 'skip' ? '⏭️' : '❌';
      console.log(`     ${icon} ${r.target} — ${r.detail}`);
    }
  }

  console.log(`\n${dryRun ? '🏜️  DRY RUN complete.' : unsync ? '✅ All IDE rule files unsynced.' : '✅ All IDE rule files synced.'}\n`);
}

main().catch(err => {
  console.error(`❌ ${err.message}`);
  process.exit(1);
});
